### ISSUE TITLE
No Covariances files found

### ISSUE THREAD

**Issue by kayobianco** [degregory/SR_manuscript#1]
Hello everyone,
I am running the command "SAM_Refiner -r Spike-Wuhan-Hu-1.fasta -S sam_file".

The indel, nt_call, and covars files are created, but the Collected_Covariances.tsv and Collected_Unique_Seqs.tsv files are not generated, and I receive the following message:

No Covariances files found
No Unique_Seqs files found
No Covar_Deconv files found
No Covar_Pass files found
No Chimeras_Removed files found

Can you help me?

**Comment by degregory** [comment]
resolved
